spring:
  profiles:
#    active: dev,commons
    active: prod,commons
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud2024?serverTimezone=GMT%2B8&characterEncoding=UTF-8
#    username: root
#    password: wzgxhcxy$%95
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl