server:
  port: 80

spring:
  application:
    name: service-gateway
#  profiles:
#    active: commons

  cloud:
    gateway:
      routes:
        - id: service-cloud-provider
          uri: lb://service-cloud-provider
          predicates:
            - Path=/*/pay/**
            - My=diamond

        - id: service-cloud-consumer
          uri: lb://service-cloud-consumer
          predicates:
            - Path=/*/order/**
