spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # gateway 可以发现 nacos 中的微服务，并自动生成转发路由
      routes:
        - id: service-cloud-consumer
          uri: lb://service-cloud-consumer
          predicates:
            - Path=/admin/order/**
        - id: service-cloud-provider
          uri: lb://service-cloud-provider
          predicates:
            - Path=/admin/pay/**